version: '3'

services:
  fastapi:
    restart: always
    image: service-restfulapi-evaluation
    ports:
      - '8000:8000'
    env_file:
      - docker/.env
    volumes:
      - /workspace/data:/home/app/workdir/data/database

  sqlite-web:
    restart: always
    image: coleifer/sqlite-web
    ports:
      - '8080:8080'
    env_file:
      - docker/.env
    volumes:
      - /workspace/data:/data